-- This file is generated by the Haskell debugger Hoed
import Properties hiding (fromList)
import qualified Debug.Hoed.Pure as Hoed
import System.Random
import Data.Maybe
import Test.QuickCheck
import XMonad.StackSet
import Test.QuickCheck
import qualified Data.Map as M
import Data.Map(fromList)
import System.Random
import Data.Maybe
main = Hoed.runOstore "prop_findIndex" $ do g <- newStdGen; print . fromJust . ok . (generate 1 g) . evaluate $ prop_findIndex  ((\r x1 x2 -> Hoed.constrain (findTag x1 x2) r)  {- generateRes -} (Nothing)  )  {- generateArgs -} (StackSet  (Screen  (Workspace  (NonNegative  ((4)) )  (error "Request of value that was unevaluated in original program (underscore 1 in computation statement).")  (Just  (Stack  (('e'))   (([]))   (([])) ) ) )   ((1))   ((1)) )   ((:)  (Screen  (Workspace  (NonNegative  ((2)) )  (error "Request of value that was unevaluated in original program (underscore 2 in computation statement).")  (Nothing) )   ((0))   ((1)) )   (([])) )   ((:)  (Workspace  (NonNegative  ((0)) )  (error "Request of value that was unevaluated in original program (underscore 3 in computation statement).")  (Nothing) )   ((:)  (Workspace  (NonNegative  ((1)) )  (error "Request of value that was unevaluated in original program (underscore 4 in computation statement).")  (Nothing) )   ((:)  (Workspace  (NonNegative  ((3)) )  (error "Request of value that was unevaluated in original program (underscore 5 in computation statement).")  (Just  (Stack  (('w'))   (([]))   (([])) ) ) )   ((:)  (Workspace  (NonNegative  ((5)) )  (error "Request of value that was unevaluated in original program (underscore 6 in computation statement).")  (Just  (Stack  (('g'))   (([]))   ((:)  (('z'))   (([])) ) ) ) )   (([])) ) ) ) )  (error "Request of value that was unevaluated in original program (underscore 7 in computation statement)."))  {- more: [Just 12: Enter (P 11 1),Just 225: Cons 0 "Nothing" (P 11 1)] -} 
