#!/bin/bash

EXAMPLES=`ls dist/build | grep hoed-examples`

i=0

echo "Available examples:"
for e in $EXAMPLES; do
  echo -n "$i) "
  echo $e | sed 's/^hoed-examples-//' |  sed 's/_/ /g'
  ((i++))
done

echo -n "Select program or -1 to cancel: "
read

# Find the appropriate example from the given input
j=0
for e in $EXAMPLES; do
  if ((j==$REPLY)); then 
    EXE=$e
    break
  fi
  ((j++))
done

# Or exit if the input was invalid (or -1)
if ((j>=i)); then
  echo "Bye"
  exit 1
fi

echo "Now executing $EXE."

# OPTS="--PushTruncate +RTS --PushTruncate"
# OPTS="--PushVanilla +RTS --PushVanilla"
# OPTS="--PushVanilla +RTS --PushHybrid"
# OPTS="--PushVanilla"

rm -f tmp/wwwroot/debugTree.png tmp/debugTree.dot
cd tmp
eval ../dist/build/$EXE/$EXE
