-- This file is generated by the Haskell debugger Hoed
import Properties
import qualified Debug.Hoed.Pure as Hoed
import System.Random
import Data.Maybe
import Test.QuickCheck
import XMonad.StackSet
import Test.QuickCheck
import qualified Data.Map as M
import System.Random
import Data.Maybe
main = Hoed.runOstore "prop_swap_right_I" $ do g <- newStdGen; print . fromJust . ok . (generate 1 g) . evaluate $ prop_swap_right_I  swapDown x (NonNegative 1)   {- generateArgs -} (StackSet  (Screen  (Workspace  (NonNegative  ((0)) )   ((-2))   (Just  (Stack  (('o'))   ((:)  (('a'))   (([])) )   ((:)  (('b'))   (([])) ) ) ) )   ((0))   ((0)) )   (([]))   (([]))   (( (M.fromList []) )) )  {- more: [Just 14: Enter (P 13 1),Just 15: Cons 4 "StackSet" (P 13 1)] -} 
